//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickMan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikePost
    {
        public int LikeID { get; set; }
        public int UserID { get; set; }
        public int PostID { get; set; }
        public Nullable<int> Likes { get; set; }
        public bool IsLike { get; set; }
    
        public virtual StickMan_Users StickMan_Users { get; set; }
        public virtual StickMan_Users_Cast_AudioData_UploadInformation StickMan_Users_Cast_AudioData_UploadInformation { get; set; }
    }
}
